Export quic_trace_id() for use in quic_meta.c
Made quic_trace_id() non-static and added declaration to quic.h
so it can be used in quic_meta.c for debug logging.

Fixes linker error: undefined reference to 'quic_trace_id'